name: Release

on:
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
 
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Run tests
        id: tests
        run: npm test
        continue-on-error: true
        
      - name: Close PR on test failure
        if: steps.tests.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo
            const pull_number = context.payload.pull_request.number
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: ` 
                This pull request was automatically closed because the tests failed.

                Please fix the issue and create a new pull request.
              
                Details provided in [Action Logs](${context.payload.repository.html_url}/actions/runs/${context.runId}).`
            })
            
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number,
              state: 'closed'
            });
            
            console.log(`PR #${pull_number} wurde wegen fehlgeschlagener Tests geschlossen.`)
            
      - name: Fail the workflow if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1